version: '2'
volumes:
    bin:
services:
  integration-service:
    container_name: scala-sbt
    image: "ica2017groepa/sascalendarservice"
    volumes:
      - "./:/opt/project"
    ports:
      - "9010:9000"
    command: ["make", "run"]
    environment:
      - "ENV=docker"
    tty: true